server:
    port: 8080
    servlet:
      context-path: /rest
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
        min-response-size: 1024
spring:
    aop:
        auto: true
        proxy-target-class: true
    devtools:
        restart:
            enabled: true
    redis:
        database: 0
        host: 127.0.0.1
        port: 6379
        jedis:
          pool:
            max-active: 100
            max-idle: 10
            max-wait: 100000
        timeout: 5000
    datasource:
          url: jdbc:mysql://127.0.0.1:3306/blog_db?useUnicode=true&characterEncoding=utf8
          username: root
          password: yzl159357
          driver-class-name: com.mysql.jdbc.Driver
          db-type: com.mysql.jdbc.Driver
          filter: stat,wall,stat,slf4j,default
          druid:
            initial-size: 5
            min-idle: 5
            max-active: 20
            max-wait: 60000
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            validation-query: SELECT 1 FROM DUAL
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            max-pool-prepared-statement-per-connection-size: 20
            filter: stat,wall,slf4j
            connection-properties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
            use-global-data-source-stat: true
            web-stat-filter:
              profile-enable: true
              enabled: true
              url-pattern: "/*"
              exclusions:
            stat-view-servlet:
              url-pattern: "/druid/*"
              # IP白名单(没有配置或者为空，则允许所有访问)
              allow: 127.0.0.1
              # IP黑名单 (存在共同时，deny优先于allow)
              deny:
              reset-enable: true
              login-password: 123456
              login-username: root
logging:
    level:
        root: info
    path: ./log
mybatis:
    type-aliases-package: com.yzl.pojo
    mapper-locations: classpath:mapper/*.xml
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
